FROM tutum/lamp:latest
RUN rm -fr /app && git clone https://github.com/WynandViljoen/Finance3.git /app
RUN chmod 777 /app/exports
RUN chmod 777 /app/uploads
RUN chmod 777 /var/lib/php5

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/apache-selfsigned.key -out /etc/ssl/certs/apache-selfsigned.crt -subj "/C=CA/ST=British Columbia/L=Vancouver/O=OrgName/OU=IT Department/CN=finance.virtualninja.ca"

COPY default-ssl.conf /etc/apache2/sites-available/default-ssl.conf
COPY 000-default.conf /etc/apache2/sites-available/000-default.conf

RUN chmod 644 /etc/ssl/certs/apache-selfsigned.crt
RUN chmod 644 /etc/ssl/private/apache-selfsigned.key


RUN a2enmod ssl
RUN a2enmod headers
RUN a2ensite default-ssl
RUN service apache2 restart

EXPOSE 80 443
CMD ["/run.sh"]